### ISSUE TITLE
Licensing Information Missing

### ISSUE THREAD

**Issue by cbonitz** [NxRLab/ModernRobotics#20]
Thank you for publishing this library.

Sadly, the repository does not contain any license statement, which is common practice on GitHub.

The [PyPI page](https://pypi.org/project/modern_robotics/) of the package mentions the MIT license. It would be great if you could add a LICENSE.txt containing the [license](https://opensource.org/licenses/MIT), with an added copyright statement, to this repo. See also [Licensing a repository](https://help.github.com/en/articles/licensing-a-repository) by GitHub.

**Comment by HuanWeng** [comment]
Thank you for reminding us! We have added it.

**Comment by cbonitz** [comment]
Thank you for adding the license.
