### ISSUE TITLE
wrong implementaiton of inverse kinematics, in the 

### ISSUE THREAD

**Issue by ertosns** [NxRLab/ModernRobotics#25]
I think there is a bug in the IKinBody, and IKinSpace, in the calculation of Vb as TransInv(T) * T, 
shouldn't Vb matrix = TransInv(T) * derivative(T) 
T = [ R P; 0 1], while derivative(T) = [ d(R) v; 0 0], the they can't equal each others, the space implementation exist in the three languages!

**Comment by HuanWeng** [comment]
Hi, I don't think there's a bug. we use the numerical algorithm described in Section 6.2.2 of the textbook.
Here we use the twist Vb to represent a motion, assuming it follows for unit time.

**Comment by ertosns** [comment]
right, that answer it.
