### ISSUE TITLE
Tool for FK and IK M and Slist parameters

### ISSUE THREAD

**Issue by LSinterbotix** [NxRLab/ModernRobotics#42]
We wrote a tool that can calculate the M and Slist parameters for Modern Robotics' kinematics functions given a kinematic chain's URDF. Functionality and performance are pretty limited at this point, but we thought it might be useful to some.

Here's the link to its repo: [kinematics_from_description](https://github.com/Interbotix/kinematics_from_description)

**Comment by tjdalsckd** [comment]
Thank you for your work
This is my code using URDF file.

https://github.com/tjdalsckd/ModernRobotics_Matlab_Example/blob/main/mr/load_urdf.m

**Comment by priscillascu** [comment]
收到，我会尽快给您答复。杨海鑫

**Comment by HuanWeng** [comment]
Thank you! The package is now mentioned in README.

**Comment by LSinterbotix** [comment]
Happy to contribute!
