### ISSUE TITLE
urdf loader for MR kinematics & dynamics 

### ISSUE THREAD

**Issue by tjdalsckd** [NxRLab/ModernRobotics#49]
I wrote a python code that can generate the M, Slist, Blist, Mlist and Glist params for MR kinematics & dynamics.
it provides ur5 simulation using pybullet.

Here's the link to its repo: [mr_urdf_loader](https://github.com/tjdalsckd/mr_urdf_loader)

**Comment by HuanWeng** [comment]
Thank you for your contribution! The package will be mentioned in README shortly.

**Comment by tjdalsckd** [comment]
Thank you!
