### ISSUE TITLE
I have question about ComputedTorque function.

### ISSUE THREAD

**Issue by sm3304love** [NxRLab/ModernRobotics#52]
![image](https://user-images.githubusercontent.com/57741032/216906109-39d6e007-ffef-4d88-9e9f-59404881be0b.png)

In `ComputedTorque` function, Why term `h(θ, ˙θ)_hat` is calculated by `InverseDynamics(thetalist, dthetalist, ddthetalistd, g, zeros(6, 1), Mlist, Glist, Slist)` instead of using `VelQuadraticForce` and `GravityForces`?

**Comment by HuanWeng** [comment]
In that function, $\tau$ is calculated as a sum of $\hat{M}(\theta)(\text{ACCELERATION-VALUE-FROM-PID-TERMS})$ and `InverseDynamics(thetalist, dthetalist, ddthetalistd, g, zeros(6, 1), Mlist, Glist, Slist)`, the later equals to $\hat{M}(\theta)\ddot{\theta_d}+\hat{h}(\theta,\dot{\theta})$.

**Comment by sm3304love** [comment]
Thank you for your answer. I have more questions. In the book, the ComputedTorque function appears to implement the formula below. Why is the last part calculated with  $\hat{M}(\theta)\ddot{\theta_d}+\hat{h}(\theta,\dot{\theta})$ in the ComputedTorque function code?

![image](https://user-images.githubusercontent.com/57741032/217147599-022dca3e-f257-4c20-8175-f53ce2cd6d51.png)
